#include "lua_backend.h"
#include <sstream>

namespace lex {

std::string LuaBackend::generate(const std::vector<std::unique_ptr<Definition>>& ast) {
    std::stringstream output;

    output << "-- Auto-generated by Lex Compiler\n";
    output << "-- Do not edit manually\n\n";

    // Generate tables for each definition type
    output << "Buildings = Buildings or {}\n";
    output << "Units = Units or {}\n";
    output << "Technologies = Technologies or {}\n";
    output << "Eras = Eras or {}\n";
    output << "Resources = Resources or {}\n\n";

    for (const auto& def : ast) {
        output << generate_definition(*def);
    }

    return output.str();
}

std::string LuaBackend::generate_definition(const Definition& def) {
    if (def.definition_type == "structure") {
        return generate_structure(def);
    } else if (def.definition_type == "unit") {
        return generate_unit(def);
    } else if (def.definition_type == "technology") {
        return generate_technology(def);
    } else if (def.definition_type == "era") {
        return generate_era(def);
    }
    return "";
}

std::string LuaBackend::generate_structure(const Definition& structure) {
    std::stringstream lua;

    lua << "Buildings." << structure.identifier << " = {\n";

    // Get era from properties
    auto era = structure.get_string_property("era");
    if (era) {
        lua << "    era = \"" << *era << "\",\n";
    }

    // Get cost if present
    const ResourceMap* cost = structure.get_resource_map_property("cost");
    if (cost) {
        lua << "    cost = " << generate_resource_map(*cost) << ",\n";
    }

    // Get production if present
    const ResourceMap* production = structure.get_resource_map_property("production");
    if (production) {
        lua << "    production = " << generate_resource_map(*production) << ",\n";
    }

    // Get maintenance if present
    const ResourceMap* maintenance = structure.get_resource_map_property("maintenance");
    if (maintenance) {
        lua << "    maintenance = " << generate_resource_map(*maintenance) << ",\n";
    }

    // Get description if present
    auto desc = structure.get_string_property("description");
    if (desc) {
        lua << "    description = [[" << *desc << "]],\n";
    }

    // Generate conditions
    if (!structure.conditions.empty()) {
        lua << "    conditions = {\n";
        for (const auto& cond : structure.conditions) {
            lua << generate_condition(cond.get());
        }
        lua << "    },\n";
    }

    lua << "}\n\n";

    // Generate condition checker function
    if (!structure.conditions.empty()) {
        lua << "function Buildings." << structure.identifier << ":check_conditions(game_state)\n";
        lua << "    local results = {}\n";
        for (const auto& cond : structure.conditions) {
            if (cond->trigger == "available_if") {
                lua << "    results.available = results.available or ("
                    << generate_expression(cond->expression.get()) << ")\n";
            }
        }
        lua << "    return results\n";
        lua << "end\n\n";
    }

    return lua.str();
}

std::string LuaBackend::generate_unit(const Definition& unit) {
    std::stringstream lua;

    lua << "Units." << unit.identifier << " = {\n";

    auto era = unit.get_string_property("era");
    if (era) {
        lua << "    era = \"" << *era << "\",\n";
    }

    auto attack = unit.get_int_property("attack");
    if (attack) {
        lua << "    attack = " << *attack << ",\n";
    }

    auto defense = unit.get_int_property("defense");
    if (defense) {
        lua << "    defense = " << *defense << ",\n";
    }

    auto movement = unit.get_int_property("movement");
    if (movement) {
        lua << "    movement = " << *movement << ",\n";
    }

    auto range = unit.get_int_property("range");
    if (range) {
        lua << "    range = " << *range << ",\n";
    }

    const ResourceMap* cost = unit.get_resource_map_property("cost");
    if (cost) {
        lua << "    cost = " << generate_resource_map(*cost) << ",\n";
    }

    auto desc = unit.get_string_property("description");
    if (desc) {
        lua << "    description = [[" << *desc << "]],\n";
    }

    // Generate conditions
    if (!unit.conditions.empty()) {
        lua << "    conditions = {\n";
        for (const auto& cond : unit.conditions) {
            lua << generate_condition(cond.get());
        }
        lua << "    },\n";
    }

    lua << "}\n\n";

    return lua.str();
}

std::string LuaBackend::generate_technology(const Definition& tech) {
    std::stringstream lua;

    lua << "Technologies." << tech.identifier << " = {\n";

    auto era = tech.get_string_property("era");
    if (era) {
        lua << "    era = \"" << *era << "\",\n";
    }

    auto research_cost = tech.get_int_property("research_cost");
    if (research_cost) {
        lua << "    research_cost = " << *research_cost << ",\n";
    }

    auto desc = tech.get_string_property("description");
    if (desc) {
        lua << "    description = [[" << *desc << "]],\n";
    }

    auto quote = tech.get_string_property("quote");
    if (quote) {
        lua << "    quote = [[" << *quote << "]],\n";
    }

    // Prerequisites
    const ReferenceList* prereqs = tech.get_reference_list_property("prerequisites");
    if (prereqs) {
        lua << "    prerequisites = " << generate_reference_list(*prereqs) << ",\n";
    }

    // Unlocks
    const ReferenceList* unlocks = tech.get_reference_list_property("unlocks");
    if (unlocks) {
        lua << "    unlocks = " << generate_reference_list(*unlocks) << ",\n";
    }

    // Generate conditions
    if (!tech.conditions.empty()) {
        lua << "    conditions = {\n";
        for (const auto& cond : tech.conditions) {
            lua << generate_condition(cond.get());
        }
        lua << "    },\n";
    }

    lua << "}\n\n";

    return lua.str();
}

std::string LuaBackend::generate_era(const Definition& era) {
    std::stringstream lua;

    lua << "Eras." << era.identifier << " = {\n";

    auto name = era.get_string_property("name");
    if (name) {
        lua << "    name = \"" << *name << "\",\n";
    }

    auto period = era.get_string_property("period");
    if (period) {
        lua << "    period = \"" << *period << "\",\n";
    }

    auto desc = era.get_string_property("description");
    if (desc) {
        lua << "    description = [[" << *desc << "]],\n";
    }

    lua << "}\n\n";

    return lua.str();
}

std::string LuaBackend::generate_resource_map(const ResourceMap& map) {
    std::string lua = "{";
    bool first = true;
    for (const auto& [name, value] : map.resources) {
        if (!first) lua += ", ";
        lua += name + " = " + std::to_string(static_cast<int>(value));
        first = false;
    }
    lua += "}";
    return lua;
}

std::string LuaBackend::generate_reference_list(const ReferenceList& list) {
    std::string lua = "{";
    bool first = true;
    for (const auto& ref : list.references) {
        if (!first) lua += ", ";
        lua += "\"" + ref + "\"";
        first = false;
    }
    lua += "}";
    return lua;
}

// ============================================================================
// Expression Generation
// ============================================================================

std::string LuaBackend::generate_expression(const Expression* expr) {
    if (!expr) return "nil";

    switch (expr->type) {
        case Expression::Type::INTEGER:
            return std::to_string(std::get<int64_t>(expr->value));

        case Expression::Type::FLOAT:
            return std::to_string(std::get<double>(expr->value));

        case Expression::Type::STRING:
            return "\"" + std::get<std::string>(expr->value) + "\"";

        case Expression::Type::BOOLEAN:
            return std::get<bool>(expr->value) ? "true" : "false";

        case Expression::Type::REFERENCE:
            // References become game_state lookups
            return "game_state." + expr->reference;

        case Expression::Type::BINARY:
            return generate_binary_expression(expr);

        case Expression::Type::UNARY:
            return generate_unary_expression(expr);

        case Expression::Type::CALL:
            return generate_call_expression(expr);

        case Expression::Type::MEMBER:
            return generate_member_expression(expr);

        case Expression::Type::COLOR:
            if (std::holds_alternative<std::string>(expr->value)) {
                return "\"" + std::get<std::string>(expr->value) + "\"";
            }
            return "\"\"";

        case Expression::Type::NULL_VAL:
        default:
            return "nil";
    }
}

std::string LuaBackend::generate_binary_expression(const Expression* expr) {
    if (!expr || !expr->left || !expr->right) return "nil";

    std::string left = generate_expression(expr->left.get());
    std::string right = generate_expression(expr->right.get());
    std::string op = binary_op_to_lua(expr->binary_op);

    return "(" + left + " " + op + " " + right + ")";
}

std::string LuaBackend::generate_unary_expression(const Expression* expr) {
    if (!expr || !expr->operand) return "nil";

    std::string operand = generate_expression(expr->operand.get());
    std::string op = unary_op_to_lua(expr->unary_op);

    return "(" + op + operand + ")";
}

std::string LuaBackend::generate_call_expression(const Expression* expr) {
    if (!expr) return "nil";

    std::string result = expr->function_name + "(";
    bool first = true;
    for (const auto& arg : expr->arguments) {
        if (!first) result += ", ";
        result += generate_expression(arg.get());
        first = false;
    }
    result += ")";
    return result;
}

std::string LuaBackend::generate_member_expression(const Expression* expr) {
    if (!expr || !expr->object) return "nil";

    std::string obj = generate_expression(expr->object.get());
    return obj + "." + expr->member_name;
}

std::string LuaBackend::generate_condition(const Condition* cond) {
    if (!cond) return "";

    std::stringstream lua;
    lua << "        " << cond->trigger << " = ";

    if (cond->expression) {
        lua << "function(game_state) return "
            << generate_expression(cond->expression.get())
            << " end,\n";
    } else {
        lua << "true,\n";
    }

    return lua.str();
}

std::string LuaBackend::generate_condition_block(const Condition* cond) {
    // For complex conditions with properties in the block
    if (!cond) return "";

    std::stringstream lua;
    lua << "        {\n";
    lua << "            trigger = \"" << cond->trigger << "\",\n";

    if (cond->expression) {
        lua << "            check = function(game_state) return "
            << generate_expression(cond->expression.get())
            << " end,\n";
    }

    for (const auto& prop : cond->properties) {
        if (prop->value && prop->value->type == PropertyValue::Type::EXPRESSION) {
            lua << "            " << prop->name << " = "
                << generate_expression(prop->value->expression.get()) << ",\n";
        }
    }

    lua << "        },\n";
    return lua.str();
}

std::string LuaBackend::binary_op_to_lua(Expression::BinaryOp op) const {
    switch (op) {
        case Expression::BinaryOp::ADD: return "+";
        case Expression::BinaryOp::SUB: return "-";
        case Expression::BinaryOp::MUL: return "*";
        case Expression::BinaryOp::DIV: return "/";
        case Expression::BinaryOp::MOD: return "%";
        case Expression::BinaryOp::EQ: return "==";
        case Expression::BinaryOp::NE: return "~=";
        case Expression::BinaryOp::GT: return ">";
        case Expression::BinaryOp::LT: return "<";
        case Expression::BinaryOp::GE: return ">=";
        case Expression::BinaryOp::LE: return "<=";
        case Expression::BinaryOp::AND: return "and";
        case Expression::BinaryOp::OR: return "or";
        default: return "+";
    }
}

std::string LuaBackend::unary_op_to_lua(Expression::UnaryOp op) const {
    switch (op) {
        case Expression::UnaryOp::NOT: return "not ";
        case Expression::UnaryOp::NEG: return "-";
        default: return "";
    }
}

// ============================================================================
// Legacy Helper implementations (using Definition accessors now)
// ============================================================================

std::string LuaBackend::get_string_property(const Definition& def, const std::string& name) {
    auto result = def.get_string_property(name);
    return result.value_or("");
}

int64_t LuaBackend::get_int_property(const Definition& def, const std::string& name, int64_t default_val) {
    auto result = def.get_int_property(name);
    return result.value_or(default_val);
}

const ResourceMap* LuaBackend::get_resource_map_property(const Definition& def, const std::string& name) {
    return def.get_resource_map_property(name);
}

}
