"""Aurelius RPC Protocol - Auto-generated handlers
Generated by Lex Compiler v1.0.0
"""

from .types_gen import *
from .server import JsonRpcServer

class RPCHandlerBase:
    """Base class for RPC handlers. Override methods to implement."""

    def handle_session_new(self, params: dict) -> dict:
        """Handle SessionNew method."""
        raise NotImplementedError("SessionNew not implemented")

    def handle_session_list(self, params: dict) -> dict:
        """Handle SessionList method."""
        raise NotImplementedError("SessionList not implemented")

    def handle_session_load(self, params: dict) -> dict:
        """Handle SessionLoad method."""
        raise NotImplementedError("SessionLoad not implemented")

    def handle_session_delete(self, params: dict) -> dict:
        """Handle SessionDelete method."""
        raise NotImplementedError("SessionDelete not implemented")

    def handle_chat_send_message(self, params: dict) -> dict:
        """Handle ChatSendMessage method."""
        raise NotImplementedError("ChatSendMessage not implemented")

    def handle_chat_abort(self, params: dict) -> dict:
        """Handle ChatAbort method."""
        raise NotImplementedError("ChatAbort not implemented")

    def handle_chat_edit_message(self, params: dict) -> dict:
        """Handle ChatEditMessage method."""
        raise NotImplementedError("ChatEditMessage not implemented")

    def handle_file_read(self, params: dict) -> dict:
        """Handle FileRead method."""
        raise NotImplementedError("FileRead not implemented")

    def handle_file_write(self, params: dict) -> dict:
        """Handle FileWrite method."""
        raise NotImplementedError("FileWrite not implemented")

    def handle_file_list(self, params: dict) -> dict:
        """Handle FileList method."""
        raise NotImplementedError("FileList not implemented")

    def handle_file_delete(self, params: dict) -> dict:
        """Handle FileDelete method."""
        raise NotImplementedError("FileDelete not implemented")

    def handle_lsp_start(self, params: dict) -> dict:
        """Handle LspStart method."""
        raise NotImplementedError("LspStart not implemented")

    def handle_lsp_diagnostics(self, params: dict) -> dict:
        """Handle LspDiagnostics method."""
        raise NotImplementedError("LspDiagnostics not implemented")

    def handle_lsp_hover(self, params: dict) -> dict:
        """Handle LspHover method."""
        raise NotImplementedError("LspHover not implemented")

    def handle_lsp_completions(self, params: dict) -> dict:
        """Handle LspCompletions method."""
        raise NotImplementedError("LspCompletions not implemented")

    def handle_lsp_definition(self, params: dict) -> dict:
        """Handle LspDefinition method."""
        raise NotImplementedError("LspDefinition not implemented")

    def handle_lsp_references(self, params: dict) -> dict:
        """Handle LspReferences method."""
        raise NotImplementedError("LspReferences not implemented")

    def handle_lsp_call_hierarchy(self, params: dict) -> dict:
        """Handle LspCallHierarchy method."""
        raise NotImplementedError("LspCallHierarchy not implemented")

    def handle_lsp_type_hierarchy(self, params: dict) -> dict:
        """Handle LspTypeHierarchy method."""
        raise NotImplementedError("LspTypeHierarchy not implemented")

    def handle_lsp_rename(self, params: dict) -> dict:
        """Handle LspRename method."""
        raise NotImplementedError("LspRename not implemented")

    def handle_lsp_workspace_symbols(self, params: dict) -> dict:
        """Handle LspWorkspaceSymbols method."""
        raise NotImplementedError("LspWorkspaceSymbols not implemented")

    def handle_mcp_list_servers(self, params: dict) -> dict:
        """Handle McpListServers method."""
        raise NotImplementedError("McpListServers not implemented")

    def handle_mcp_list_tools(self, params: dict) -> dict:
        """Handle McpListTools method."""
        raise NotImplementedError("McpListTools not implemented")

    def handle_settings_get(self, params: dict) -> dict:
        """Handle SettingsGet method."""
        raise NotImplementedError("SettingsGet not implemented")

    def handle_settings_set(self, params: dict) -> dict:
        """Handle SettingsSet method."""
        raise NotImplementedError("SettingsSet not implemented")

    def handle_models_list(self, params: dict) -> dict:
        """Handle ModelsList method."""
        raise NotImplementedError("ModelsList not implemented")

    def handle_agent_run(self, params: dict) -> dict:
        """Handle AgentRun method."""
        raise NotImplementedError("AgentRun not implemented")

    def handle_agent_summarize(self, params: dict) -> dict:
        """Handle AgentSummarize method."""
        raise NotImplementedError("AgentSummarize not implemented")



def register_handlers(server: JsonRpcServer, handler: RPCHandlerBase):
    """Register all RPC handlers with the server."""

    def handle_session_new_wrapper(params: dict) -> dict:
        return handler.handle_session_new(params)
    server.register("SessionNew", handle_session_new_wrapper)

    def handle_session_list_wrapper(params: dict) -> dict:
        return handler.handle_session_list(params)
    server.register("SessionList", handle_session_list_wrapper)

    def handle_session_load_wrapper(params: dict) -> dict:
        return handler.handle_session_load(params)
    server.register("SessionLoad", handle_session_load_wrapper)

    def handle_session_delete_wrapper(params: dict) -> dict:
        return handler.handle_session_delete(params)
    server.register("SessionDelete", handle_session_delete_wrapper)

    def handle_chat_send_message_wrapper(params: dict) -> dict:
        return handler.handle_chat_send_message(params)
    server.register("ChatSendMessage", handle_chat_send_message_wrapper)

    def handle_chat_abort_wrapper(params: dict) -> dict:
        return handler.handle_chat_abort(params)
    server.register("ChatAbort", handle_chat_abort_wrapper)

    def handle_chat_edit_message_wrapper(params: dict) -> dict:
        return handler.handle_chat_edit_message(params)
    server.register("ChatEditMessage", handle_chat_edit_message_wrapper)

    def handle_file_read_wrapper(params: dict) -> dict:
        return handler.handle_file_read(params)
    server.register("FileRead", handle_file_read_wrapper)

    def handle_file_write_wrapper(params: dict) -> dict:
        return handler.handle_file_write(params)
    server.register("FileWrite", handle_file_write_wrapper)

    def handle_file_list_wrapper(params: dict) -> dict:
        return handler.handle_file_list(params)
    server.register("FileList", handle_file_list_wrapper)

    def handle_file_delete_wrapper(params: dict) -> dict:
        return handler.handle_file_delete(params)
    server.register("FileDelete", handle_file_delete_wrapper)

    def handle_lsp_start_wrapper(params: dict) -> dict:
        return handler.handle_lsp_start(params)
    server.register("LspStart", handle_lsp_start_wrapper)

    def handle_lsp_diagnostics_wrapper(params: dict) -> dict:
        return handler.handle_lsp_diagnostics(params)
    server.register("LspDiagnostics", handle_lsp_diagnostics_wrapper)

    def handle_lsp_hover_wrapper(params: dict) -> dict:
        return handler.handle_lsp_hover(params)
    server.register("LspHover", handle_lsp_hover_wrapper)

    def handle_lsp_completions_wrapper(params: dict) -> dict:
        return handler.handle_lsp_completions(params)
    server.register("LspCompletions", handle_lsp_completions_wrapper)

    def handle_lsp_definition_wrapper(params: dict) -> dict:
        return handler.handle_lsp_definition(params)
    server.register("LspDefinition", handle_lsp_definition_wrapper)

    def handle_lsp_references_wrapper(params: dict) -> dict:
        return handler.handle_lsp_references(params)
    server.register("LspReferences", handle_lsp_references_wrapper)

    def handle_lsp_call_hierarchy_wrapper(params: dict) -> dict:
        return handler.handle_lsp_call_hierarchy(params)
    server.register("LspCallHierarchy", handle_lsp_call_hierarchy_wrapper)

    def handle_lsp_type_hierarchy_wrapper(params: dict) -> dict:
        return handler.handle_lsp_type_hierarchy(params)
    server.register("LspTypeHierarchy", handle_lsp_type_hierarchy_wrapper)

    def handle_lsp_rename_wrapper(params: dict) -> dict:
        return handler.handle_lsp_rename(params)
    server.register("LspRename", handle_lsp_rename_wrapper)

    def handle_lsp_workspace_symbols_wrapper(params: dict) -> dict:
        return handler.handle_lsp_workspace_symbols(params)
    server.register("LspWorkspaceSymbols", handle_lsp_workspace_symbols_wrapper)

    def handle_mcp_list_servers_wrapper(params: dict) -> dict:
        return handler.handle_mcp_list_servers(params)
    server.register("McpListServers", handle_mcp_list_servers_wrapper)

    def handle_mcp_list_tools_wrapper(params: dict) -> dict:
        return handler.handle_mcp_list_tools(params)
    server.register("McpListTools", handle_mcp_list_tools_wrapper)

    def handle_settings_get_wrapper(params: dict) -> dict:
        return handler.handle_settings_get(params)
    server.register("SettingsGet", handle_settings_get_wrapper)

    def handle_settings_set_wrapper(params: dict) -> dict:
        return handler.handle_settings_set(params)
    server.register("SettingsSet", handle_settings_set_wrapper)

    def handle_models_list_wrapper(params: dict) -> dict:
        return handler.handle_models_list(params)
    server.register("ModelsList", handle_models_list_wrapper)

    def handle_agent_run_wrapper(params: dict) -> dict:
        return handler.handle_agent_run(params)
    server.register("AgentRun", handle_agent_run_wrapper)

    def handle_agent_summarize_wrapper(params: dict) -> dict:
        return handler.handle_agent_summarize(params)
    server.register("AgentSummarize", handle_agent_summarize_wrapper)