// Code generated by Lex Compiler v1.0.0. DO NOT EDIT.
// Package rpc provides JSON-RPC types for Aurelius.

package rpc

// AgentResult represents the AgentResult RPC type.
type AgentResult struct {
    Response interface{} `json:"response"`
    SessionId string `json:"session_id"`
}

// AgentRunRequest represents the AgentRunRequest RPC type.
type AgentRunRequest struct {
    SessionId string `json:"session_id"`
    Prompt string `json:"prompt"`
    Attachments []Attachment `json:"attachments"`
}

// AgentSummarizeRequest represents the AgentSummarizeRequest RPC type.
type AgentSummarizeRequest struct {
    SessionId string `json:"session_id"`
}

// Attachment represents the Attachment RPC type.
type Attachment struct {
    Type string `json:"type"`
    Path string `json:"path"`
    Content string `json:"content"`
}

// CallHierarchyItem represents the CallHierarchyItem RPC type.
type CallHierarchyItem struct {
    Name string `json:"name"`
    Kind int64 `json:"kind"`
    Uri string `json:"uri"`
    Range Range `json:"range"`
    SelectionRange Range `json:"selection_range"`
}

// CallHierarchyResponse represents the CallHierarchyResponse RPC type.
type CallHierarchyResponse struct {
    Item CallHierarchyItem `json:"item"`
    Incoming []CallHierarchyItem `json:"incoming"`
    Outgoing []CallHierarchyItem `json:"outgoing"`
}

// ChatAbortRequest represents the ChatAbortRequest RPC type.
type ChatAbortRequest struct {
    MessageId string `json:"message_id"`
}

// ChatEditMessageRequest represents the ChatEditMessageRequest RPC type.
type ChatEditMessageRequest struct {
    SessionIdentifier string `json:"session_identifier"`
    MessageId string `json:"message_id"`
    NewContent string `json:"new_content"`
}

// ChatSendMessageRequest represents the ChatSendMessageRequest RPC type.
type ChatSendMessageRequest struct {
    SessionIdentifier string `json:"session_identifier"`
    Content string `json:"content"`
    Attachments []Attachment `json:"attachments"`
}

// ChatSendMessageResponse represents the ChatSendMessageResponse RPC type.
type ChatSendMessageResponse struct {
    Message Message `json:"message"`
    SessionIdentifier string `json:"session_identifier"`
}

// CompletionItem represents the CompletionItem RPC type.
type CompletionItem struct {
    Label string `json:"label"`
    Kind int64 `json:"kind"`
    Detail string `json:"detail"`
    Documentation string `json:"documentation"`
    InsertText string `json:"insert_text"`
}

// ContentPart represents the ContentPart RPC type.
type ContentPart struct {
    Type string `json:"type"`
    Text string `json:"text"`
}

// Diagnostic represents the Diagnostic RPC type.
type Diagnostic struct {
    Range Range `json:"range"`
    Severity int64 `json:"severity"`
    Message string `json:"message"`
    Source string `json:"source"`
    Code string `json:"code"`
}

// Empty represents the Empty RPC type.
type Empty struct {
}

// FileDeleteRequest represents the FileDeleteRequest RPC type.
type FileDeleteRequest struct {
    Path string `json:"path"`
}

// FileInfo represents the FileInfo RPC type.
type FileInfo struct {
    Name string `json:"name"`
    Path string `json:"path"`
    Type string `json:"type"`
    Size int64 `json:"size"`
    Modified string `json:"modified"`
}

// FileListRequest represents the FileListRequest RPC type.
type FileListRequest struct {
    Path string `json:"path"`
    Recursive bool `json:"recursive"`
    IncludeHidden bool `json:"include_hidden"`
}

// FileListResponse represents the FileListResponse RPC type.
type FileListResponse struct {
    Files []FileInfo `json:"files"`
}

// FileReadRequest represents the FileReadRequest RPC type.
type FileReadRequest struct {
    Path string `json:"path"`
    Encoding string `json:"encoding"`
}

// FileReadResponse represents the FileReadResponse RPC type.
type FileReadResponse struct {
    Content string `json:"content"`
    Encoding string `json:"encoding"`
    Size int64 `json:"size"`
}

// FileWriteRequest represents the FileWriteRequest RPC type.
type FileWriteRequest struct {
    Path string `json:"path"`
    Content string `json:"content"`
    Encoding string `json:"encoding"`
}

// HoverInfo represents the HoverInfo RPC type.
type HoverInfo struct {
    Contents string `json:"contents"`
    Range *Range `json:"range"`
}

// Location represents the Location RPC type.
type Location struct {
    Uri string `json:"uri"`
    Range Range `json:"range"`
}

// LspCompletionsResponse represents the LspCompletionsResponse RPC type.
type LspCompletionsResponse struct {
    Completions []CompletionItem `json:"completions"`
}

// LspDiagnosticsRequest represents the LspDiagnosticsRequest RPC type.
type LspDiagnosticsRequest struct {
    Uri string `json:"uri"`
}

// LspDiagnosticsResponse represents the LspDiagnosticsResponse RPC type.
type LspDiagnosticsResponse struct {
    Diagnostics []Diagnostic `json:"diagnostics"`
}

// LspHoverResponse represents the LspHoverResponse RPC type.
type LspHoverResponse struct {
    Hover *HoverInfo `json:"hover"`
}

// LspLocationsResponse represents the LspLocationsResponse RPC type.
type LspLocationsResponse struct {
    Locations []Location `json:"locations"`
}

// LspPositionRequest represents the LspPositionRequest RPC type.
type LspPositionRequest struct {
    FilePath string `json:"file_path"`
    Line int64 `json:"line"`
    Character int64 `json:"character"`
}

// LspRenameRequest represents the LspRenameRequest RPC type.
type LspRenameRequest struct {
    FilePath string `json:"file_path"`
    Line int64 `json:"line"`
    Character int64 `json:"character"`
    NewName string `json:"new_name"`
}

// LspRenameResponse represents the LspRenameResponse RPC type.
type LspRenameResponse struct {
    Changes []TextEdit `json:"changes"`
}

// LspStartRequest represents the LspStartRequest RPC type.
type LspStartRequest struct {
    Language string `json:"language"`
    Cwd string `json:"cwd"`
}

// LspStartResponse represents the LspStartResponse RPC type.
type LspStartResponse struct {
    Success bool `json:"success"`
    Language string `json:"language"`
    ServerName string `json:"server_name"`
}

// LspWorkspaceSymbolsRequest represents the LspWorkspaceSymbolsRequest RPC type.
type LspWorkspaceSymbolsRequest struct {
    Query string `json:"query"`
    FileType string `json:"file_type"`
}

// LspWorkspaceSymbolsResponse represents the LspWorkspaceSymbolsResponse RPC type.
type LspWorkspaceSymbolsResponse struct {
    Symbols []SymbolInfo `json:"symbols"`
}

// McpListServersResponse represents the McpListServersResponse RPC type.
type McpListServersResponse struct {
    Servers []McpServer `json:"servers"`
}

// McpListToolsRequest represents the McpListToolsRequest RPC type.
type McpListToolsRequest struct {
    ServerName string `json:"server_name"`
}

// McpListToolsResponse represents the McpListToolsResponse RPC type.
type McpListToolsResponse struct {
    Tools []McpTool `json:"tools"`
}

// McpServer represents the McpServer RPC type.
type McpServer struct {
    Name string `json:"name"`
    Status string `json:"status"`
    ToolsCount int64 `json:"tools_count"`
}

// McpTool represents the McpTool RPC type.
type McpTool struct {
    Name string `json:"name"`
    Description string `json:"description"`
    InputSchema interface{} `json:"input_schema"`
}

// Message represents the Message RPC type.
type Message struct {
    Identifier string `json:"identifier"`
    Role string `json:"role"`
    Parts []MessagePart `json:"parts"`
    CreatedAt string `json:"created_at"`
}

// MessagePart represents the MessagePart RPC type.
type MessagePart struct {
    Type string `json:"type"`
    Text string `json:"text"`
    Content string `json:"content"`
}

// Model represents the Model RPC type.
type Model struct {
    Id string `json:"id"`
    Name string `json:"name"`
    Provider string `json:"provider"`
    ContextWindow int64 `json:"context_window"`
    SupportsStreaming bool `json:"supports_streaming"`
    SupportsVision bool `json:"supports_vision"`
}

// ModelsListResponse represents the ModelsListResponse RPC type.
type ModelsListResponse struct {
    Models []Model `json:"models"`
}

// Position represents the Position RPC type.
type Position struct {
    Line int64 `json:"line"`
    Character int64 `json:"character"`
}

// Range represents the Range RPC type.
type Range struct {
    Start Position `json:"start"`
    End Position `json:"end"`
}

// Session represents the Session RPC type.
type Session struct {
    SessionIdentifier string `json:"session_identifier"`
    Name string `json:"name"`
    CreatedAt string `json:"created_at"`
    Cwd string `json:"cwd"`
    MessageCount int64 `json:"message_count"`
}

// SessionDeleteRequest represents the SessionDeleteRequest RPC type.
type SessionDeleteRequest struct {
    SessionIdentifier string `json:"session_identifier"`
}

// SessionListResponse represents the SessionListResponse RPC type.
type SessionListResponse struct {
    Sessions []Session `json:"sessions"`
}

// SessionLoadRequest represents the SessionLoadRequest RPC type.
type SessionLoadRequest struct {
    SessionIdentifier string `json:"session_identifier"`
}

// SessionNewRequest represents the SessionNewRequest RPC type.
type SessionNewRequest struct {
    Name string `json:"name"`
    Cwd string `json:"cwd"`
}

// SettingsResponse represents the SettingsResponse RPC type.
type SettingsResponse struct {
    Model string `json:"model"`
    ThinkingEnabled bool `json:"thinking_enabled"`
    Cwd string `json:"cwd"`
    Theme string `json:"theme"`
}

// SettingsSetRequest represents the SettingsSetRequest RPC type.
type SettingsSetRequest struct {
    Key string `json:"key"`
    Value interface{} `json:"value"`
}

// SuccessResponse represents the SuccessResponse RPC type.
type SuccessResponse struct {
    Success bool `json:"success"`
}

// SymbolInfo represents the SymbolInfo RPC type.
type SymbolInfo struct {
    Name string `json:"name"`
    Kind int64 `json:"kind"`
    ContainerName string `json:"container_name"`
    Location Location `json:"location"`
}

// TextEdit represents the TextEdit RPC type.
type TextEdit struct {
    Range Range `json:"range"`
    NewText string `json:"new_text"`
}

// TypeHierarchyResponse represents the TypeHierarchyResponse RPC type.
type TypeHierarchyResponse struct {
    Item CallHierarchyItem `json:"item"`
    Supertypes []CallHierarchyItem `json:"supertypes"`
    Subtypes []CallHierarchyItem `json:"subtypes"`
}



// Code generated by Lex Compiler v1.0.0. DO NOT EDIT.

package rpc

import "context"

// Client provides JSON-RPC client methods.
type Client interface {
    SessionNew(ctx context.Context, req *SessionNewRequest) (*Session, error)
    SessionList(ctx context.Context, req *Empty) (*SessionListResponse, error)
    SessionLoad(ctx context.Context, req *SessionLoadRequest) (*Session, error)
    SessionDelete(ctx context.Context, req *SessionDeleteRequest) (*SuccessResponse, error)
    ChatSendMessage(ctx context.Context, req *ChatSendMessageRequest) (*ChatSendMessageResponse, error)
    ChatAbort(ctx context.Context, req *ChatAbortRequest) (*SuccessResponse, error)
    ChatEditMessage(ctx context.Context, req *ChatEditMessageRequest) (*SuccessResponse, error)
    FileRead(ctx context.Context, req *FileReadRequest) (*FileReadResponse, error)
    FileWrite(ctx context.Context, req *FileWriteRequest) (*SuccessResponse, error)
    FileList(ctx context.Context, req *FileListRequest) (*FileListResponse, error)
    FileDelete(ctx context.Context, req *FileDeleteRequest) (*SuccessResponse, error)
    LspStart(ctx context.Context, req *LspStartRequest) (*LspStartResponse, error)
    LspDiagnostics(ctx context.Context, req *LspDiagnosticsRequest) (*LspDiagnosticsResponse, error)
    LspHover(ctx context.Context, req *LspPositionRequest) (*LspHoverResponse, error)
    LspCompletions(ctx context.Context, req *LspPositionRequest) (*LspCompletionsResponse, error)
    LspDefinition(ctx context.Context, req *LspPositionRequest) (*LspLocationsResponse, error)
    LspReferences(ctx context.Context, req *LspPositionRequest) (*LspLocationsResponse, error)
    LspCallHierarchy(ctx context.Context, req *LspPositionRequest) (*CallHierarchyResponse, error)
    LspTypeHierarchy(ctx context.Context, req *LspPositionRequest) (*TypeHierarchyResponse, error)
    LspRename(ctx context.Context, req *LspRenameRequest) (*LspRenameResponse, error)
    LspWorkspaceSymbols(ctx context.Context, req *LspWorkspaceSymbolsRequest) (*LspWorkspaceSymbolsResponse, error)
    McpListServers(ctx context.Context, req *Empty) (*McpListServersResponse, error)
    McpListTools(ctx context.Context, req *McpListToolsRequest) (*McpListToolsResponse, error)
    SettingsGet(ctx context.Context, req *Empty) (*SettingsResponse, error)
    SettingsSet(ctx context.Context, req *SettingsSetRequest) (*SuccessResponse, error)
    ModelsList(ctx context.Context, req *Empty) (*ModelsListResponse, error)
    AgentRun(ctx context.Context, req *AgentRunRequest) (*AgentResult, error)
    AgentSummarize(ctx context.Context, req *AgentSummarizeRequest) (*SuccessResponse, error)
}