#!/usr/bin/env python3
"""Split the generated .rpc file into types_gen.py and handlers_gen.py"""

import re

with open('aurelius_rpc_simplified.rpc', 'r', encoding='utf-8') as f:
    content = f.read()

# Split by section markers
parts = re.split(r'=== PYTHON ===|=== GO ===', content)

if len(parts) >= 3:
    python_code = parts[1].strip()
    go_code = parts[2].strip()
    
    # Find where handlers section starts
    handlers_start = python_code.find('class RPCHandlerBase')
    
    if handlers_start > 0:
        types_code = python_code[:handlers_start].strip()
        handlers_code = python_code[handlers_start:].strip()
        
        # Write types_gen.py
        with open('types_gen.py', 'w', encoding='utf-8') as f:
            f.write(types_code + '\n')
        
        # Write handlers_gen.py with proper imports
        with open('handlers_gen.py', 'w', encoding='utf-8') as f:
            f.write('''"""Aurelius RPC Protocol - Auto-generated handlers
Generated by Lex Compiler v1.0.0
"""

from .types_gen import *
from .server import JsonRpcServer

''')
            f.write(handlers_code + '\n')
        
        # Write Go file
        with open('rpc_types.go', 'w', encoding='utf-8') as f:
            f.write(go_code + '\n')
        
        print(f'Created types_gen.py ({len(types_code)} chars)')
        print(f'Created handlers_gen.py ({len(handlers_code)} chars)')
        print(f'Created rpc_types.go ({len(go_code)} chars)')
    else:
        print('ERROR: Could not find handlers section')
else:
    print(f'ERROR: Could not parse file (found {len(parts)} parts)')
