"""
Aurelius RPC Protocol - Auto-generated types
Generated by Lex Compiler v1.0.0
"""

from dataclasses import dataclass
from typing import List, Optional, Dict, Any

@dataclass
class AgentResult:
    response: object
    session_id: str

@dataclass
class AgentRunRequest:
    session_id: str
    prompt: str
    attachments: List[Attachment]

@dataclass
class AgentSummarizeRequest:
    session_id: str

@dataclass
class Attachment:
    type: str
    path: str
    content: str

@dataclass
class CallHierarchyItem:
    name: str
    kind: int
    uri: str
    range: Range
    selection_range: Range

@dataclass
class CallHierarchyResponse:
    item: CallHierarchyItem
    incoming: List[CallHierarchyItem]
    outgoing: List[CallHierarchyItem]

@dataclass
class ChatAbortRequest:
    message_id: str

@dataclass
class ChatEditMessageRequest:
    session_identifier: str
    message_id: str
    new_content: str

@dataclass
class ChatSendMessageRequest:
    session_identifier: str
    content: str
    attachments: List[Attachment]

@dataclass
class ChatSendMessageResponse:
    message: Message
    session_identifier: str

@dataclass
class CompletionItem:
    label: str
    kind: int
    detail: str
    documentation: str
    insert_text: str

@dataclass
class ContentPart:
    type: str
    text: str

@dataclass
class Diagnostic:
    range: Range
    severity: int
    message: str
    source: str
    code: str

@dataclass
class Empty:
    pass

@dataclass
class FileDeleteRequest:
    path: str

@dataclass
class FileInfo:
    name: str
    path: str
    type: str
    size: int
    modified: str

@dataclass
class FileListRequest:
    path: str
    recursive: bool
    include_hidden: bool

@dataclass
class FileListResponse:
    files: List[FileInfo]

@dataclass
class FileReadRequest:
    path: str
    encoding: str

@dataclass
class FileReadResponse:
    content: str
    encoding: str
    size: int

@dataclass
class FileWriteRequest:
    path: str
    content: str
    encoding: str

@dataclass
class HoverInfo:
    contents: str
    range: Optional[Range]

@dataclass
class Location:
    uri: str
    range: Range

@dataclass
class LspCompletionsResponse:
    completions: List[CompletionItem]

@dataclass
class LspDiagnosticsRequest:
    uri: str

@dataclass
class LspDiagnosticsResponse:
    diagnostics: List[Diagnostic]

@dataclass
class LspHoverResponse:
    hover: Optional[HoverInfo]

@dataclass
class LspLocationsResponse:
    locations: List[Location]

@dataclass
class LspPositionRequest:
    file_path: str
    line: int
    character: int

@dataclass
class LspRenameRequest:
    file_path: str
    line: int
    character: int
    new_name: str

@dataclass
class LspRenameResponse:
    changes: List[TextEdit]

@dataclass
class LspStartRequest:
    language: str
    cwd: str

@dataclass
class LspStartResponse:
    success: bool
    language: str
    server_name: str

@dataclass
class LspWorkspaceSymbolsRequest:
    query: str
    file_type: str

@dataclass
class LspWorkspaceSymbolsResponse:
    symbols: List[SymbolInfo]

@dataclass
class McpListServersResponse:
    servers: List[McpServer]

@dataclass
class McpListToolsRequest:
    server_name: str

@dataclass
class McpListToolsResponse:
    tools: List[McpTool]

@dataclass
class McpServer:
    name: str
    status: str
    tools_count: int

@dataclass
class McpTool:
    name: str
    description: str
    input_schema: object

@dataclass
class Message:
    identifier: str
    role: str
    parts: List[MessagePart]
    created_at: str

@dataclass
class MessagePart:
    type: str
    text: str
    content: str

@dataclass
class Model:
    id: str
    name: str
    provider: str
    context_window: int
    supports_streaming: bool
    supports_vision: bool

@dataclass
class ModelsListResponse:
    models: List[Model]

@dataclass
class Position:
    line: int
    character: int

@dataclass
class Range:
    start: Position
    end: Position

@dataclass
class Session:
    session_identifier: str
    name: str
    created_at: str
    cwd: str
    message_count: int

@dataclass
class SessionDeleteRequest:
    session_identifier: str

@dataclass
class SessionListResponse:
    sessions: List[Session]

@dataclass
class SessionLoadRequest:
    session_identifier: str

@dataclass
class SessionNewRequest:
    name: str
    cwd: str

@dataclass
class SettingsResponse:
    model: str
    thinking_enabled: bool
    cwd: str
    theme: str

@dataclass
class SettingsSetRequest:
    key: str
    value: object

@dataclass
class SuccessResponse:
    success: bool

@dataclass
class SymbolInfo:
    name: str
    kind: int
    container_name: str
    location: Location

@dataclass
class TextEdit:
    range: Range
    new_text: str

@dataclass
class TypeHierarchyResponse:
    item: CallHierarchyItem
    supertypes: List[CallHierarchyItem]
    subtypes: List[CallHierarchyItem]



"""